#!/bin/sh

iDIR="$HOME/.config/dunst/assets/ui"

get_backlight() {
	MAX=$(brightnessctl max)
	LIGHT=$(printf "%.0f\n" $(brightnessctl get))
	PERCENTAGE=$(expr 100 \* $LIGHT / $MAX)
	echo "${PERCENTAGE}%"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if ("$current" -ge "0"); then icon="$iDIR/brightness_up.png"
	elif ("$current" -le "100") then icon="$iDIR/brightness_down.png"
	fi
}

# Not Used but keeped for future implementations
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)"
}

down() {
brightnessctl set 5%- && get_icon
brightness="$(get_backlight)"
dunstify -a "BRIGHTNESS" "Decreasing to $brightness" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
brightnessctl set 5%+ && get_icon
brightness="$(get_backlight)"
dunstify -a "BRIGHTNESS" "Increasing to $brightness" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
