#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
#systemctl --user restart xdg-desktop-portal.service
#sleep 2 && /usr/libexec/xdg-desktop-portal-hyprland -r