#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

dir="$HOME/.config/rofi/scripts"
theme='style'

wallpapers=$HOME/.config/hypr/wallpapers
image="$(ls $wallpapers | rofi -dmenu -i -p "  Select wallpaper: " -theme ${dir}/${theme}.rasi)"
wallpaper=$wallpapers/$image

# Save the new wallpepers so Hyprland will pick it up next boot
echo $wallpapers/$image > $HOME/.cache/mywall

if [[ -d $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a directory"
    wallpaper_temp="$image"
    sleep2
    wallpaper_location="$(ls $wallpapers/$image | wofi -n --show dmenu -k "/dev/null")"
elif [[ -f $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a file"
else
    echo "$wallpapers/$image is not valid"
    exit 1
fi

swww kill

swww init

swww img $wallpaper --transition-type grow --transition-fps 60 --transition-duration 1.0 --transition-bezier 0.65,0,0.35,1 --transition-step 255

echo $wallpaper
wal -i $wallpaper --cols16
pywalfox update
pywal-discord -t default
wal-telegram --wal

. $HOME/.config/spicetify/Themes/Pywal/update-colors.sh
. $HOME/.config/cava/scripts/update-colors.sh
